---
- name: Deploy Flask App in Docker
  hosts: webserver
  become: yes  # Run as sudo/root
  gather_facts: no  # Skip initial fact gathering which would use the wrong Python
  
  pre_tasks:
    - name: Set Python 3.8 as interpreter
      raw: which python3.8
      register: python_path
      changed_when: false
      
    - name: Set Python for Ansible
      set_fact:
        ansible_python_interpreter: "{{ python_path.stdout_lines[0] }}"
      
    - name: Gather facts with correct Python
      setup:
  
  tasks:
    - name: Install required system packages
      command: yum install -y python3 python3-pip
      # The 'warn' parameter is not supported, so we've removed it
    
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
    
    - name: Create a directory for the Flask app
      file:
        path: /home/ec2-user/flask-app
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'
    
    - name: Copy Flask app files to the server
      copy:
        src: ../flask-app/
        dest: /home/ec2-user/flask-app/
        owner: ec2-user
        group: ec2-user
        mode: '0644'
    
    - name: Build Docker image
      command:
        cmd: docker build -t flask-app .
        chdir: /home/ec2-user/flask-app
    
    - name: Stop and remove existing container (if running)
      command: docker rm -f my-flask-app
      ignore_errors: yes
    
    - name: Run Flask app in a container
      command:
        cmd: docker run -d -p 80:80 --name my-flask-app flask-app
