name: Test Secrets

on:
  workflow_dispatch:  # Allows manual execution

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Test AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws sts get-caller-identity || echo "AWS Credentials Failed!"

      - name: Check Private Key
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" | base64 --decode > test-key.pem
          chmod 600 test-key.pem
          ls -l test-key.pem
